# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questionUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QApplication


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(690, 478)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.graphicsView = QtWidgets.QGraphicsView(dialog)
        self.graphicsView.setGeometry(QtCore.QRect(130, 60, 411, 91))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalScrollBar = QtWidgets.QScrollBar(dialog)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(90, 170, 501, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 31))
        self.label.setObjectName("label")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(dialog)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(80, 340, 501, 20))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 211, 31))
        self.label_2.setObjectName("label_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(120, 230, 411, 91))
        self.graphicsView_2.setObjectName("graphicsView_2")

        self.retranslateUi(dialog)
        self.buttonBox.accepted.connect(dialog.accept)
        self.buttonBox.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label.setText(_translate("dialog", "TextLabel"))
        self.label_2.setText(_translate("dialog", "TextLabel"))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    ui = uic.loadUi("./questionUI.ui")
    # 展示窗口
    ui.show()

    app.exec()