# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Video")
        MainWindow.resize(563, 335)
        MainWindow.setMinimumSize(QtCore.QSize(563, 335))
        MainWindow.setMaximumSize(QtCore.QSize(563, 335))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wgt_player = QVideoWidget(self.centralwidget)
        self.wgt_player.setGeometry(QtCore.QRect(30, 30, 501, 241))
        self.wgt_player.setStyleSheet("border-radius:7px;\n"
                                      "background-color: rgb(197, 197, 197);")
        self.wgt_player.setObjectName("wgt_player")
        self.btn_play_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play_pause.setGeometry(QtCore.QRect(30, 292, 21, 21))
        self.btn_play_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play_pause.setStyleSheet("border:none;\n"
                                          "image: url(:/imge/暂停.png);")
        self.btn_play_pause.setText("")
        self.btn_play_pause.setObjectName("btn_play_pause")
        self.sld_duration = QtWidgets.QSlider(self.centralwidget)
        self.sld_duration.setGeometry(QtCore.QRect(30, 275, 501, 16))
        self.sld_duration.setStyleSheet("QSlider::groove:horizontal {\n"
                                        "        height: 2.5px;\n"
                                        "margin: 0px 0;  \n"
                                        "        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(203, 203, 203), stop: 1.0 rgb(203, 203, 203));\n"
                                        "}\n"
                                        "QSlider::handle:horizontal {\n"
                                        "        width: 9px;\n"
                                        "        height: 5px;\n"
                                        "    background-color: rgb(44, 44, 44);\n"
                                        "        margin: -5px 0px -5px 0px;\n"
                                        "     border-radius:4px;\n"
                                        "}\n"
                                        "  \n"
                                        "     QSlider::add-page:Horizontal\n"
                                        "     {     \n"
                                        "        \n"
                                        "        height:4px;\n"
                                        "     }\n"
                                        "     QSlider::sub-page:Horizontal \n"
                                        "    {\n"
                                        "        \n"
                                        "    background-color: rgb(0, 170, 255);\n"
                                        "        height:4px;\n"
                                        "     }\\\n"
                                        "    QSlider::groove:Horizontal\n"
                                        "    {\\\n"
                                        "        background:transparent;\n"
                                        "        height:6px;\n"
                                        "    }\\\n"
                                        "    QSlider::handle:Horizontal \n"
                                        "    {\n"
                                        "        height: 30px;\n"
                                        "        width:8px;\n"
                                        "        margin: -8 0px; \n"
                                        "    }\n"
                                        "")
        self.sld_duration.setMaximum(1000)
        self.sld_duration.setOrientation(QtCore.Qt.Horizontal)
        self.sld_duration.setObjectName("sld_duration")
        self.lab_duration = QtWidgets.QLabel(self.centralwidget)
        self.lab_duration.setGeometry(QtCore.QRect(60, 292, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lab_duration.setFont(font)
        self.lab_duration.setObjectName("lab_duration")
        self.btn_select = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select.setGeometry(QtCore.QRect(470, 290, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_select.setFont(font)
        self.btn_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select.setStyleSheet("border:none;\n"
                                      "background-color:rgb(153, 153, 153);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "border-radius:4px;")
        self.btn_select.setObjectName("btn_select")
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setGeometry(QtCore.QRect(390, 290, 71, 20))
        self.volumeSlider.setStyleSheet("QSlider::groove:horizontal {\n"
                                        "        height: 2.5px;\n"
                                        "margin: 0px 0;  \n"
                                        "        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(203, 203, 203), stop: 1.0 rgb(203, 203, 203));\n"
                                        "}\n"
                                        "QSlider::handle:horizontal {\n"
                                        "        width: 9px;\n"
                                        "        height: 5px;\n"
                                        "    background-color: rgb(44, 44, 44);\n"
                                        "        margin: -5px 0px -5px 0px;\n"
                                        "     border-radius:4px;\n"
                                        "}\n"
                                        "  \n"
                                        "     QSlider::add-page:Horizontal\n"
                                        "     {     \n"
                                        "        \n"
                                        "        height:4px;\n"
                                        "     }\n"
                                        "     QSlider::sub-page:Horizontal \n"
                                        "    {\n"
                                        "        \n"
                                        "    background-color: rgb(0, 170, 255);\n"
                                        "        height:4px;\n"
                                        "     }\\\n"
                                        "    QSlider::groove:Horizontal\n"
                                        "    {\\\n"
                                        "        background:transparent;\n"
                                        "        height:6px;\n"
                                        "    }\\\n"
                                        "    QSlider::handle:Horizontal \n"
                                        "    {\n"
                                        "        height: 30px;\n"
                                        "        width:8px;\n"
                                        "        margin: -8 0px; \n"
                                        "    }\n"
                                        "")
        self.volumeSlider.setMaximum(10)
        self.volumeSlider.setProperty("value", 8)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.imge = QtWidgets.QLabel(self.centralwidget)
        self.imge.setGeometry(QtCore.QRect(360, 290, 31, 21))
        self.imge.setStyleSheet("image: url(:/imge/volume.png);")
        self.imge.setText("")
        self.imge.setObjectName("imge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyVideo"))
        self.lab_duration.setText(_translate("MainWindow", "--:--"))
        self.btn_select.setText(_translate("MainWindow", "选择视频"))


from PyQt5.QtMultimediaWidgets import QVideoWidget
